/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TrainingRegistration } from "./TrainingRegistration";
import { TrainingRegistrationCountArgs } from "./TrainingRegistrationCountArgs";
import { TrainingRegistrationFindManyArgs } from "./TrainingRegistrationFindManyArgs";
import { TrainingRegistrationFindUniqueArgs } from "./TrainingRegistrationFindUniqueArgs";
import { DeleteTrainingRegistrationArgs } from "./DeleteTrainingRegistrationArgs";
import { TrainingRegistrationService } from "../trainingRegistration.service";
@graphql.Resolver(() => TrainingRegistration)
export class TrainingRegistrationResolverBase {
  constructor(protected readonly service: TrainingRegistrationService) {}

  async _trainingRegistrationsMeta(
    @graphql.Args() args: TrainingRegistrationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TrainingRegistration])
  async trainingRegistrations(
    @graphql.Args() args: TrainingRegistrationFindManyArgs
  ): Promise<TrainingRegistration[]> {
    return this.service.trainingRegistrations(args);
  }

  @graphql.Query(() => TrainingRegistration, { nullable: true })
  async trainingRegistration(
    @graphql.Args() args: TrainingRegistrationFindUniqueArgs
  ): Promise<TrainingRegistration | null> {
    const result = await this.service.trainingRegistration(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TrainingRegistration)
  async deleteTrainingRegistration(
    @graphql.Args() args: DeleteTrainingRegistrationArgs
  ): Promise<TrainingRegistration | null> {
    try {
      return await this.service.deleteTrainingRegistration(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
